server: Add missing include <cstdint>
Fails to build with musl libc and gcc 15 because uint32_t is used
without including cstdint:

In file included from sarge.cpp:17:
sarge.h:54:30: error: 'uint32_t' has not been declared
   54 |         bool getTextArgument(uint32_t index, std::string &value);
      |                              ^~~~~~~~
sarge.h:22:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   21 | #include <memory>
  +++ |+#include <cstdint>
   22 |